Add support for sssd-/realmd-based domain-join
plus3it/join-domain-formula pull request #167
Opened 2023-02-07 23:11 UTC by ferricoxide

closes #166 

Notes:
- only verified with EL7
- The SEL-toggle _should_ only be necessary for EL7 (EL8+ have necessary SEL-policies)
- Leverages same inputs as PBIS (the `…/sssd/map.jinja` file is a copy of the PBIS service's) …but adds the `pkg_map` OS-keyed dictionary to select OS_VERS-appropriate RPM-list
- It is not yet known whether `sssd`/`realmd` integration will require the same kind of collisions-abatement logic that PBIS did

2023-02-08 21:26 UTC, lorengordon requested changes
Ok, a handful of suggestions. And also:

* Update `pillar.example` with inputs for `sssd`
* Update `README.md` to cover `sssd` usage

2023-02-08 21:26 UTC, lorengordon commented on join-domain/elx/sssd/files/join.sh
> +  fi
The [shellcheck docs](https://www.shellcheck.net/wiki/SC2181) suggest doing assignment inline in the if test. Maybe something like this?

```suggestion
  # Get cleartext password-string
  if PWCLEAR=$(
    echo "${PWCRYPT}" | \
    openssl enc -aes-256-cbc -md sha256 -a -d -salt -pass pass:"${PWUNLOCK}"
  )
  then
    echo "${PWCLEAR}"
    return 0
  else
    echo ""
    return 1
  fi
```

2023-02-08 21:26 UTC, lorengordon commented on join-domain/elx/sssd/files/join.sh
> +    echo "$( PWdecrypt )" | \
The [shellcheck doc](https://www.shellcheck.net/wiki/SC2005) suggests we should be able to just call the function, since the function echoes the value we don't need this wrapping echo... If that works, same change on line 85-86

```suggestion
    PWdecrypt | \
```

2023-02-08 21:26 UTC, lorengordon commented on join-domain/elx/sssd/files/join.sh
> +set -eu
Does this still work if we also add pipefail?

```suggestion
set -eu -o pipefail
```

2023-02-08 21:26 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
> +    - unless: 'realm list | grep {{ join_domain.dns_name }}'
Salt's output might be a tad cleaner if we suppress the output from the unless test
```suggestion
    - unless: 'realm list | grep -qs {{ join_domain.dns_name }}'
```

2023-02-08 21:26 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
I'd be a bit more comfortable if we make all these state explicitly require one another, instead of relying on the implicit/not-guaranteed top-down processing...

```suggestion
          override_space: '^'
    - require:
      - pkg: install_sssd
```

2023-02-09 10:36 UTC, ferricoxide commented on join-domain/elx/sssd/map.jinja
> +  - Local_LoginShellTemplate
I'd simply copied and extended the `maps.jinja` from the `pbis` connector and extended it with the sssd-specific stuff. Lemme nuke out the PBIS-only stuff.

2023-02-09 10:43 UTC, ferricoxide commented on join-domain/elx/sssd/init.sls
> +          override_homedir: '/home/%d/%u'
You can, but it defaults to `/bin/bash`, already (which is the value we want).

2023-02-09 11:05 UTC, ferricoxide commented on join-domain/elx/sssd/files/join.sh
> +  fi
Unfortunately, if the `openssl enc …` operation fails (e.g., because the key and encrypted-string are mismatched), `PWCLEAR` will still have _a_ value (just the _wrong_ value – a binary-stream). Had to resort to the `if [[ $? -ne 0 ]]` kludge to be extra sure that the test-statement evaluated based _solely_ on the process's return code and not simply whether `PWCLEAR` had _a_ value

2023-02-09 11:09 UTC, ferricoxide commented on join-domain/elx/sssd/init.sls
While I can see the why one would attempt to assert this dependency, it's worth noting that `install_sssd`  will still return a success-status to the `require` if _any_ RPM in the request-list is successfully resolved (at least on EL7). So, the actual value of asserting the explicit dependency may be significantly reduced.

2023-02-09 11:15 UTC, ferricoxide commented on join-domain/elx/sssd/init.sls
The _really_ weird thing, here, is I remember having set:

```

    - require:
      - ini: 'fix_domain_separator'
      - ini: 'domain_defaults-{{ join_domain.dns_name }}'
```

For the `join_realm-…` state (memorable because I wasn't sure whether i needed to reference `ini:` or `options_present`)

Not sure where the asserted `requires` statements disappeared to? They may not have made the jump from my dev EC2 to my commit-signing host (as they were a final addition before I did the signing-`amend` and I may have failed to fully refresh my commit-signing host's local repository-copy).

2023-02-09 11:39 UTC, ferricoxide commented on join-domain/elx/sssd/files/join.sh
> +    echo "$( PWdecrypt )" | \
Yeah,  shellcheck bitched at me about it. However, in testing (on EL7), doing the naked `PWdecrypt` resulted in failure (thus the commit-note in commit acc000362b5f614897719cc31202afb9cad44915 ☹️). Unfortunately, unlike with PBIS, there is no flag for `realm join …` that allows you to just include the string as an argument in the command-invocation, itself – you have to resort to an `echo <STRING> | realm join …` kludgery. It would seem that shellcheck is wrong about the method: whether that's a function of the elderliness of  EL7's version of BASH or how `realm join` reads from `STDIN` I have no clue, but it was the necessary method.

2023-02-09 11:41 UTC, ferricoxide commented on join-domain/elx/sssd/init.sls
> +    - unless: 'realm list | grep {{ join_domain.dns_name }}'
Bleah... I'd _had_ `grep -q …` at one point in the process.

2023-02-09 11:44 UTC, ferricoxide commented on join-domain/elx/sssd/files/join.sh
> +set -eu
I'd had it with `-o pipefail` early on (and was starting this `join.sh` as a copy of PBIS's), but may have lost it when I decided to start from scratch.

2023-02-09 18:33 UTC, lorengordon reviewed
Just a couple more comments... Any changes to README.md?

And can you confirm statefulness, that executing the `join-domain` state a second time does not fail or ortherwise break anything?

2023-02-09 18:33 UTC, lorengordon commented on join-domain/elx/init.sls
> +    'sssd'
Don't forget to set this back to `pbis` for now...
```suggestion
    'pbis'
```

2023-02-09 18:33 UTC, lorengordon commented on join-domain/elx/sssd/files/join.sh
> +  fi
Take another look at the suggested change... My understanding is that even if openssl outputs junk in that case, it is _still_ returning an error exit, which means the if test will fail and the `else` clause will be effective and the function will echo the empty string and return 1.

2023-02-09 18:33 UTC, lorengordon commented on join-domain/elx/sssd/files/join.sh
> +    echo "$( PWdecrypt )" | \
That's fine, just wanted to check we at least tried.

2023-02-09 18:33 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
> install_sssd will still return a success-status to the require if any RPM in the request-list is successfully resolved (at least on EL7)

Hrm... it really _shouldn't_ be doing that... it should be testing for each specified package, and it should fail if a specified package is not installed... I'd like to maybe spend a little more time investigating/understanding what is going on there, please. Maybe there is an issue on saltstack github about that.

2023-02-10 11:26 UTC, ferricoxide commented on join-domain/elx/sssd/init.sls
We've been down this package before: you previously got bitten by the "why didn't this error when one of the N packages I  requested weren't able installed" problem. _EL7's_ `yum` is dumb (EL8's `dnf`, on the other hand, is smarter). It only considers things an error if _none_ of the requested packages are available.

2023-02-10 14:39 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
Yeah I understand the yum/dnf el7/el8 part of it. That's not what I was talking about, exactly, though. _Salt_ does extra checks to ensure that what you asked it to do, is what ended up happening. When you install an rpm, it should not just run yum/dnf and accept the exit code. It should check afterwards that the rpm is present. If it is not, then Salt is not doing what it should be doing, and there should be an issue for it, or perhaps an option we aren't yet using to make it behave the way we want.

2023-02-10 15:32 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
> +          default_shell: '/bin/bash'
Let's use the value coming from defaults/pillar, instead of hardcoding...

```suggestion
          default_shell: '{{ join_domain.login_shell }}'
```

2023-02-10 15:32 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
> +          shell_fallback: '/bin/bash'
```suggestion
          shell_fallback: '{{ join_domain.login_shell }}'
```

2023-02-10 21:28 UTC, lorengordon commented on join-domain/elx/init.sls
> +    salt.grains.filter_by(connect_default, grain='osmajorrelease')
You know I like this approach 😁

2023-02-10 21:32 UTC, lorengordon commented on join-domain/elx/init.sls
> +{%- set pkg_map = {
Why do we have this `pkg_map` and `pkg_list` both here and in `els/sssd/map.jinja`?

2023-02-10 21:34 UTC, lorengordon commented on join-domain/elx/init.sls
> +{%- set pkg_map = {
Yeah, I don't see anything using this. We're only getting the `pkg_list` from `elx/sssd/map.jinja`, so this can be removed.

2023-02-10 21:36 UTC, lorengordon commented on join-domain/elx/sssd/init.sls
> +      - pkg: install_sssd
Ooops, this require is duplicated...
```suggestion
```

2023-02-13 10:30 UTC, ferricoxide commented on join-domain/elx/init.sls
> +{%- set pkg_map = {
I'm not seeing anything in my shell history to explain it, but, "gone now".

2023-02-13 10:33 UTC, ferricoxide commented on join-domain/elx/sssd/init.sls
> +      - pkg: install_sssd
Nuking the later one: generally prefer my parameters to be as close to alphabetical order as I can (and `require:` comes before `sections:`)

2023-02-13 14:10 UTC, lorengordon approved these changes
🚢

2023-02-13 16:17 UTC, merged